/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState } from "react";
import { ResearchPaper, User, ResearchNote } from "../types";
import { 
  BookOpen, Bookmark, Download, Upload, Trash2, ArrowRight, ShieldCheck, 
  GraduationCap, FileText, BookmarkX, Edit2, Save, X, Loader2, 
  Activity, Check, ExternalLink, Share2, Award, BookMarked
} from "lucide-react";
import { motion, AnimatePresence } from "motion/react";

const SUPABASE_SETUP_SQL = `-- 1. Create custom profiles table
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  updated_at timestamp with time zone,
  full_name text,
  avatar_url text
);

-- 2. Create custom bookmarks table
create table if not exists public.bookmarks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  paper_id text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (user_id, paper_id)
);

-- 3. Create custom notes table
create table if not exists public.notes (
  id text primary key,
  user_id uuid references auth.users on delete cascade not null,
  paper_id text not null,
  paper_title text not null,
  category text not null,
  note_text text not null,
  updated_at text not null
);

-- 4. Enable Row Level Security (RLS) for privacy
alter table public.profiles enable row level security;
alter table public.bookmarks enable row level security;
alter table public.notes enable row level security;

-- 5. Access Policies (Only users themselves can view/edit their own data)
drop policy if exists "Public profiles are viewable by everyone" on public.profiles;
create policy "Public profiles are viewable by everyone" on public.profiles for select using (true);

drop policy if exists "Users can insert their own profile" on public.profiles;
create policy "Users can insert their own profile" on public.profiles for insert with check (auth.uid() = id);

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile" on public.profiles for update using (auth.uid() = id);

drop policy if exists "Users can see only their own bookmarks" on public.bookmarks;
create policy "Users can see only their own bookmarks" on public.bookmarks for select using (auth.uid() = user_id);

drop policy if exists "Users can manage their own bookmarks" on public.bookmarks;
create policy "Users can manage their own bookmarks" on public.bookmarks for all using (auth.uid() = user_id);

drop policy if exists "Users can see only their own notes" on public.notes;
create policy "Users can see only their own notes" on public.notes for select using (auth.uid() = user_id);

drop policy if exists "Users can manage their own notes" on public.notes;
create policy "Users can manage their own notes" on public.notes for all using (auth.uid() = user_id);`;

interface MyLibraryProps {
  papers: ResearchPaper[];
  bookmarks: string[];
  downloads: string[];
  history: string[];
  notes: ResearchNote[];
  onDeleteNote: (id: string) => void;
  onSaveNote: (paperId: string, paperTitle: string, category: string, noteText: string) => void;
  currentUser: User | null;
  onReadPaper: (paper: ResearchPaper) => void;
  onRemoveBookmark: (paperId: string) => void;
  onDownloadPaper: (paper: ResearchPaper) => void;
  onUpdatePaper: (updatedPaper: ResearchPaper) => Promise<void>;
  onDeletePaper: (paperId: string) => Promise<void>;
}

export default function MyLibrary({
  papers,
  bookmarks,
  downloads,
  history,
  notes = [],
  onDeleteNote,
  onSaveNote,
  currentUser,
  onReadPaper,
  onRemoveBookmark,
  onDownloadPaper,
  onUpdatePaper,
  onDeletePaper
}: MyLibraryProps) {
  const [activeTab, setActiveTab] = useState<"uploads" | "bookmarks" | "downloads" | "history" | "notes">("bookmarks");
  const [showSchemaGuide, setShowSchemaGuide] = useState(false);
  const [copiedSql, setCopiedSql] = useState(false);

  // Editing paper state
  const [editingPaper, setEditingPaper] = useState<ResearchPaper | null>(null);
  const [editTitle, setEditTitle] = useState("");
  const [editAuthors, setEditAuthors] = useState("");
  const [editSchool, setEditSchool] = useState("");
  const [editAbstract, setEditAbstract] = useState("");
  const [editCategory, setEditCategory] = useState("");
  const [isSaving, setIsSaving] = useState(false);

  const startEditing = (paper: ResearchPaper) => {
    setEditingPaper(paper);
    setEditTitle(paper.title);
    setEditAuthors(paper.authors.join(", "));
    setEditSchool(paper.schools[0] || "");
    setEditAbstract(paper.abstract);
    setEditCategory(paper.category);
  };

  const handleSaveEdit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!editingPaper) return;
    setIsSaving(true);
    try {
      await onUpdatePaper({
        ...editingPaper,
        title: editTitle,
        authors: editAuthors.split(",").map(a => a.trim()).filter(Boolean),
        schools: [editSchool],
        abstract: editAbstract,
        category: editCategory
      });
      setEditingPaper(null);
    } catch (err) {
      console.error("Error updating paper:", err);
    } finally {
      setIsSaving(false);
    }
  };

  // Filter papers matching each tab category
  const uploadedPapers = papers.filter((p) => p.externalSource === "Student Upload");
  const bookmarkedPapers = papers.filter((p) => bookmarks.includes(p.id));
  const downloadedPapers = papers.filter((p) => downloads.includes(p.id));
  const readHistoryPapers = papers.filter((p) => history.includes(p.id));

  const getTabCount = (tab: "uploads" | "bookmarks" | "downloads" | "history" | "notes") => {
    switch (tab) {
      case "uploads": return uploadedPapers.length;
      case "bookmarks": return bookmarkedPapers.length;
      case "downloads": return downloadedPapers.length;
      case "history": return readHistoryPapers.length;
      case "notes": return notes.length;
    }
  };

  return (
    <div className="w-full space-y-6" id="my-library-page">
      {/* Page Header */}
      <div className="vibrant-glass rounded-2xl p-6 shadow-2xl flex flex-col md:flex-row md:items-center justify-between gap-4 border border-white/20">
        <div>
          <span className="text-[10px] font-mono uppercase bg-cyan-400/10 text-cyan-300 border border-cyan-400/30 px-2.5 py-1 rounded font-bold tracking-wide">
            Personal Desk
          </span>
          <h2 className="font-display font-extrabold text-stone-100 text-lg md:text-xl mt-3.5 flex items-center gap-2">
            My Academic Library
            <span className="text-xs bg-slate-950/40 text-cyan-300 border border-white/10 px-2.5 py-0.5 rounded-full font-sans font-extrabold">
              {bookmarks.length + uploadedPapers.length} Records Indexed
            </span>
          </h2>
          <p className="text-stone-100 text-xs mt-1.5 font-bold leading-relaxed">
            Organize, monitor, and download your bookmarked and uploaded research manuscripts.
          </p>
        </div>

        <div className="flex gap-6 border-l-0 md:border-l border-slate-800 pl-0 md:pl-6 text-xs text-stone-100 font-mono font-bold">
          <div>
            <div className="text-stone-300 font-bold">Published</div>
            <div className="text-stone-100 font-black text-sm mt-0.5">{uploadedPapers.length}</div>
          </div>
          <div>
            <div className="text-stone-300 font-bold">Bookmarked</div>
            <div className="text-stone-100 font-black text-sm mt-0.5">{bookmarkedPapers.length}</div>
          </div>
          <div>
            <div className="text-stone-300 font-bold">Downloads</div>
            <div className="text-stone-100 font-black text-sm mt-0.5">{downloadedPapers.length}</div>
          </div>
        </div>
      </div>

      {/* Supabase Schema Developer Assistant */}
      <div className="flex justify-end relative z-10" id="schema-guide-container">
        <button
          onClick={() => setShowSchemaGuide(!showSchemaGuide)}
          className="text-[10px] font-mono uppercase bg-indigo-500/10 hover:bg-indigo-500/20 text-indigo-300 border border-indigo-500/30 px-3.5 py-1.5 rounded-xl font-bold flex items-center gap-1.5 transition-all cursor-pointer shadow-sm active:scale-[0.98]"
          id="toggle-schema-guide-btn"
        >
          <Award className="w-3.5 h-3.5 text-cyan-400" />
          <span>{showSchemaGuide ? "Hide Supabase SQL Schema" : "Setup Private Supabase"}</span>
        </button>
      </div>

      <AnimatePresence>
        {showSchemaGuide && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: "auto" }}
            exit={{ opacity: 0, height: 0 }}
            transition={{ duration: 0.2 }}
            className="vibrant-glass border border-indigo-500/20 rounded-2xl p-5 md:p-6 space-y-4 overflow-hidden relative z-10"
            id="supabase-schema-guide-card"
          >
            <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4">
              <div className="space-y-1">
                <h3 className="text-xs font-bold text-white flex items-center gap-1.5 uppercase tracking-wider font-display">
                  <ShieldCheck className="w-4 h-4 text-emerald-400 shrink-0" />
                  Configure Your Own Supabase Tables
                </h3>
                <p className="text-stone-400 text-[11px] leading-relaxed">
                  To sync bookmarks, history, profiles, and research notes perfectly to your private Supabase backend database, execute the SQL code below in your <b>Supabase SQL Editor</b>.
                </p>
              </div>
              <button
                type="button"
                onClick={() => {
                  navigator.clipboard.writeText(SUPABASE_SETUP_SQL);
                  setCopiedSql(true);
                  setTimeout(() => setCopiedSql(false), 2000);
                }}
                className="bg-emerald-600 hover:bg-emerald-500 text-white font-mono font-bold text-[10px] uppercase tracking-wider px-3.5 py-2.5 rounded-xl flex items-center justify-center gap-1.5 transition-all shrink-0 cursor-pointer shadow-md active:scale-[0.98]"
              >
                {copiedSql ? <Check className="w-3.5 h-3.5" /> : <Save className="w-3.5 h-3.5" />}
                <span>{copiedSql ? "Copied SQL!" : "Copy SQL Script"}</span>
              </button>
            </div>

            <div className="relative">
              <pre className="w-full text-[10px] font-mono bg-black/60 border border-white/5 rounded-xl p-4 overflow-x-auto text-emerald-300 max-h-48 leading-relaxed select-all">
                {SUPABASE_SETUP_SQL}
              </pre>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Dynamic Scholar Analytics Bento Dashboard */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-5" id="scholar-analytics-dashboard">
        {/* Card 1: Study Goals & Streaks */}
        <div className="vibrant-glass-bright border border-white/10 rounded-2xl p-5 flex items-center justify-between shadow-lg relative overflow-hidden">
          <div className="space-y-2 relative z-10">
            <span className="text-[9px] font-mono uppercase bg-emerald-500/15 text-emerald-300 border border-emerald-500/30 px-2 py-0.5 rounded-full font-bold">
              Study Metrics
            </span>
            <h4 className="font-display font-extrabold text-stone-100 text-xs md:text-sm mt-1">Astra Reading Target</h4>
            <p className="text-stone-200 text-[11px] font-bold leading-snug">
              Read 3 premium papers per day to level up your global research index.
            </p>
            <div className="flex gap-4 mt-3 text-[10px] font-mono text-stone-100 font-bold">
              <div>
                <span className="text-stone-300 font-bold block">Streak</span>
                <span className="text-amber-400 font-black text-xs">🔥 4 Days</span>
              </div>
              <div>
                <span className="text-stone-300 font-bold block">Current Rank</span>
                <span className="text-cyan-300 font-black text-xs">Scholar Apprentice</span>
              </div>
            </div>
          </div>

          {/* SVG Glow Progress Dial */}
          {(() => {
            const dailyTarget = 3;
            const currentCount = Math.min(dailyTarget, readHistoryPapers.length);
            const radius = 28;
            const circumference = 2 * Math.PI * radius;
            const strokeDashoffset = circumference - (currentCount / dailyTarget) * circumference;
            return (
              <div className="relative w-20 h-20 flex items-center justify-center shrink-0">
                <svg className="w-full h-full transform -rotate-90">
                  {/* Track ring */}
                  <circle
                    cx="40"
                    cy="40"
                    r={radius}
                    className="stroke-slate-800"
                    strokeWidth="5"
                    fill="transparent"
                  />
                  {/* Progress ring */}
                  <circle
                    cx="40"
                    cy="40"
                    r={radius}
                    className="stroke-cyan-400 drop-shadow-[0_0_8px_rgba(34,211,238,0.5)] transition-all duration-1000 ease-out"
                    strokeWidth="5"
                    fill="transparent"
                    strokeDasharray={circumference}
                    strokeDashoffset={strokeDashoffset}
                    strokeLinecap="round"
                  />
                </svg>
                <div className="absolute flex flex-col items-center">
                  <span className="text-xs font-black font-mono text-stone-100">{currentCount}/{dailyTarget}</span>
                  <span className="text-[8px] font-mono text-stone-300 uppercase font-black">Goal</span>
                </div>
              </div>
            );
          })()}
        </div>

        {/* Card 2: Field Domain Allocations */}
        <div className="vibrant-glass-bright border border-white/10 rounded-2xl p-5 flex flex-col justify-between shadow-lg md:col-span-1">
          <div>
            <div className="flex items-center justify-between mb-1.5">
              <span className="text-[9px] font-mono uppercase bg-indigo-500/15 text-indigo-300 border border-indigo-500/30 px-2 py-0.5 rounded-full font-bold">
                Domain Allocation
              </span>
              <span className="text-[10px] text-stone-200 font-mono font-black flex items-center gap-1">
                <Activity className="w-3.5 h-3.5 text-indigo-400 animate-pulse" /> Live Mapping
              </span>
            </div>
            <h4 className="font-display font-extrabold text-stone-100 text-xs md:text-sm">Research Fields Directory</h4>
          </div>

          {bookmarkedPapers.length === 0 ? (
            <p className="text-[11px] text-stone-300 font-bold italic leading-relaxed py-2">
              No bookmarked fields registered yet. Map your scholarly realm by bookmarking papers.
            </p>
          ) : (
            <div className="space-y-2 mt-2">
              {(() => {
                const categoryCounts: Record<string, number> = {};
                bookmarkedPapers.forEach(p => {
                  categoryCounts[p.category] = (categoryCounts[p.category] || 0) + 1;
                });
                const total = bookmarkedPapers.length;
                const sorted = Object.entries(categoryCounts)
                  .sort((a, b) => b[1] - a[1])
                  .slice(0, 2);

                const barColors = ["bg-cyan-400", "bg-purple-500", "bg-yellow-400"];
                return (
                  <div className="space-y-1.5">
                    {/* Compact list with progress bars */}
                    {sorted.map(([cat, count], idx) => {
                      const percent = Math.round((count / total) * 100);
                      return (
                        <div key={cat} className="space-y-0.5">
                          <div className="flex justify-between text-[9px] font-black text-stone-200">
                            <span className="truncate max-w-[130px] font-bold">{cat}</span>
                            <span className="font-bold">{percent}%</span>
                          </div>
                          <div className="w-full h-1 bg-slate-900 rounded-full overflow-hidden">
                            <div className={`h-full ${barColors[idx % barColors.length]} rounded-full`} style={{ width: `${percent}%` }} />
                          </div>
                        </div>
                      );
                    })}

                    {/* Integrated horizontal segmented mapping */}
                    <div className="flex h-1.5 w-full rounded-full overflow-hidden bg-slate-900 mt-2">
                      {Object.entries(categoryCounts).map(([cat, count], idx) => {
                        const percent = (count / total) * 100;
                        const colors = ["bg-cyan-400", "bg-purple-500", "bg-yellow-400", "bg-emerald-400", "bg-rose-400"];
                        return (
                          <div
                            key={cat}
                            className={`${colors[idx % colors.length]} h-full`}
                            style={{ width: `${percent}%` }}
                            title={`${cat}: ${percent}%`}
                          />
                        );
                      })}
                    </div>
                  </div>
                );
              })()}
            </div>
          )}
        </div>

        {/* Card 3: Knowledge Metrics & Portfolio Value */}
        <div className="vibrant-glass-bright border border-white/10 rounded-2xl p-5 flex flex-col justify-between shadow-lg">
          <div className="flex items-center justify-between mb-1.5">
            <span className="text-[9px] font-mono uppercase bg-blue-500/15 text-blue-300 border border-blue-500/30 px-2 py-0.5 rounded-full font-bold">
              Scholarly Footprint
            </span>
            <Award className="w-4 h-4 text-amber-400 animate-pulse" />
          </div>

          <div className="grid grid-cols-3 gap-2 py-1 text-center font-mono">
            <div className="bg-slate-950/45 p-2 rounded-xl border border-white/5">
              <span className="text-[9px] text-stone-300 block uppercase font-black">Total Depth</span>
              <span className="text-xs md:text-sm font-black text-stone-100">
                {history.length * 12} <span className="text-[8px] text-stone-300 font-extrabold">pgs</span>
              </span>
            </div>
            <div className="bg-slate-950/45 p-2 rounded-xl border border-white/5">
              <span className="text-[9px] text-stone-300 block uppercase font-black">Study Notes</span>
              <span className="text-xs md:text-sm font-black text-cyan-300">{notes.length}</span>
            </div>
            <div className="bg-slate-950/45 p-2 rounded-xl border border-white/5">
              <span className="text-[9px] text-stone-300 block uppercase font-black">DOIs Held</span>
              <span className="text-xs md:text-sm font-black text-indigo-300">{uploadedPapers.length}</span>
            </div>
          </div>

          <p className="text-[10px] text-stone-200 font-bold leading-tight mt-2.5">
            💡 <strong>Pro Tip:</strong> Click the "Export Note" button in your Notes tab to save annotations directly as local markdown files.
          </p>
        </div>
      </div>

      {/* Library Tabs */}
      <div className="flex border-b border-slate-800/80 gap-2 overflow-x-auto pb-1 scrollbar-hide">
        <button
          onClick={() => setActiveTab("bookmarks")}
          className={`px-5 py-3 text-xs font-bold uppercase tracking-wider border-b-2 transition-all duration-300 cursor-pointer flex items-center gap-2 shrink-0 ${
            activeTab === "bookmarks"
              ? "border-blue-500 text-blue-400 font-extrabold font-mono"
              : "border-transparent text-stone-300 hover:text-blue-400 font-bold font-mono"
          }`}
        >
          <Bookmark className="w-4 h-4 text-blue-400" />
          My Bookmarks ({getTabCount("bookmarks")})
        </button>
        <button
          onClick={() => setActiveTab("uploads")}
          className={`px-5 py-3 text-xs font-bold uppercase tracking-wider border-b-2 transition-all duration-300 cursor-pointer flex items-center gap-2 shrink-0 ${
            activeTab === "uploads"
              ? "border-blue-500 text-blue-400 font-extrabold font-mono"
              : "border-transparent text-stone-300 hover:text-blue-400 font-bold font-mono"
          }`}
        >
          <Upload className="w-4 h-4 text-blue-400" />
          My Uploads ({getTabCount("uploads")})
        </button>
        <button
          onClick={() => setActiveTab("downloads")}
          className={`px-5 py-3 text-xs font-bold uppercase tracking-wider border-b-2 transition-all duration-300 cursor-pointer flex items-center gap-2 shrink-0 ${
            activeTab === "downloads"
              ? "border-blue-500 text-blue-400 font-extrabold font-mono"
              : "border-transparent text-stone-300 hover:text-blue-400 font-bold font-mono"
          }`}
        >
          <Download className="w-4 h-4 text-blue-400" />
          Downloaded ({getTabCount("downloads")})
        </button>
        <button
          onClick={() => setActiveTab("history")}
          className={`px-5 py-3 text-xs font-bold uppercase tracking-wider border-b-2 transition-all duration-300 cursor-pointer flex items-center gap-2 shrink-0 ${
            activeTab === "history"
              ? "border-blue-500 text-blue-400 font-extrabold font-mono"
              : "border-transparent text-stone-300 hover:text-blue-400 font-bold font-mono"
          }`}
        >
          <BookOpen className="w-4 h-4 text-blue-400" />
          Read History ({getTabCount("history")})
        </button>
        <button
          onClick={() => setActiveTab("notes")}
          className={`px-5 py-3 text-xs font-bold uppercase tracking-wider border-b-2 transition-all duration-300 cursor-pointer flex items-center gap-2 shrink-0 ${
            activeTab === "notes"
              ? "border-blue-500 text-blue-400 font-extrabold font-mono"
              : "border-transparent text-stone-300 hover:text-blue-400 font-bold font-mono"
          }`}
        >
          <FileText className="w-4 h-4 text-blue-400" />
          Research Notes ({getTabCount("notes")})
        </button>
      </div>

      {/* Lists */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4" id="library-paper-grid">
        
        {/* Bookmarks Tab */}
        {activeTab === "bookmarks" && (
          bookmarkedPapers.length > 0 ? (
            bookmarkedPapers.map((paper) => (
              <motion.div
                key={paper.id}
                layoutId={`library-bookmark-${paper.id}`}
                className="vibrant-glass-bright border border-white/10 hover:border-cyan-400/50 rounded-2xl p-5 flex flex-col justify-between hover:shadow-[0_0_20px_rgba(34,211,238,0.12)] transition-all duration-300"
              >
                <div>
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-[9px] font-mono uppercase bg-cyan-400/10 text-cyan-300 border border-cyan-400/30 px-2.5 py-1 rounded font-bold">
                      {paper.category}
                    </span>
                    <button
                      onClick={() => onRemoveBookmark(paper.id)}
                      className="text-stone-200 hover:text-rose-400 hover:bg-rose-500/10 border border-slate-800/80 hover:border-rose-500/40 transition-all duration-300 p-2 rounded-xl cursor-pointer transform hover:scale-[1.08] hover:shadow-[0_0_12px_rgba(244,63,94,0.15)] font-bold"
                      title="Remove Bookmark"
                    >
                      <BookmarkX className="w-4 h-4" />
                    </button>
                  </div>
                  <h3 className="font-display font-extrabold text-stone-100 text-sm md:text-base leading-snug mb-1.5 hover:text-blue-400 transition-colors cursor-pointer" onClick={() => onReadPaper(paper)}>
                    {paper.title}
                  </h3>
                  <p className="text-[11px] text-stone-200 font-sans mb-3 font-black">
                    By {paper.authors.join(", ")} | {paper.schools[0]}
                  </p>
                  <p className="text-stone-100 text-xs font-bold line-clamp-2 leading-relaxed mb-4">
                    {paper.abstract}
                  </p>
                </div>

                <div className="flex items-center justify-between pt-3.5 border-t border-slate-850 mt-auto">
                  <span className="text-[10px] text-stone-300 font-mono font-bold">
                    Published {paper.publishedDate}
                  </span>
                  <div className="flex gap-2">
                    <button
                      onClick={() => onDownloadPaper(paper)}
                      className="p-2.5 bg-slate-950/80 hover:bg-slate-900 border border-slate-800 hover:border-cyan-500/50 text-stone-300 rounded-xl transition-all duration-300 cursor-pointer hover:text-cyan-400 transform hover:scale-[1.05] hover:shadow-[0_0_12px_rgba(6,182,212,0.15)] font-bold"
                      title="Download PDF"
                    >
                      <Download className="w-4 h-4" />
                    </button>
                    <button
                      onClick={() => onReadPaper(paper)}
                      className="px-4 py-2 animated-gradient-btn text-white rounded-full text-xs font-extrabold flex items-center gap-1 cursor-pointer"
                    >
                      Read Now <ArrowRight className="w-3.5 h-3.5" />
                    </button>
                  </div>
                </div>
              </motion.div>
            ))
          ) : (
            <div className="col-span-2 text-center py-16 bg-white/5 border border-white/15 rounded-2xl">
              <Bookmark className="w-10 h-10 text-stone-300 mx-auto mb-3 animate-pulse" />
              <p className="text-stone-100 text-sm font-black">Your library is empty</p>
              <p className="text-stone-300 text-xs mt-1 font-bold">Bookmarked papers will appear here for fast-track reading.</p>
            </div>
          )
        )}

        {/* Uploads Tab */}
        {activeTab === "uploads" && (
          uploadedPapers.length > 0 ? (
            uploadedPapers.map((paper) => (
              <motion.div
                key={paper.id}
                layoutId={`library-upload-${paper.id}`}
                className="vibrant-glass-bright border border-white/10 hover:border-cyan-400/50 rounded-2xl p-5 flex flex-col justify-between hover:shadow-[0_0_20px_rgba(34,211,238,0.12)] transition-all duration-300"
              >
                <div>
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-[9px] font-mono uppercase bg-emerald-500/10 text-emerald-400 border border-emerald-500/30 px-2.5 py-1 rounded flex items-center gap-1 font-bold">
                      <ShieldCheck className="w-3 h-3 text-emerald-400" />
                      DOI Registered
                    </span>
                    <span className="text-[10px] text-stone-200 font-mono font-black">
                      Student-Authored
                    </span>
                  </div>
                  <h3 className="font-display font-extrabold text-stone-100 text-sm md:text-base leading-snug mb-1.5 hover:text-blue-400 transition-colors cursor-pointer" onClick={() => onReadPaper(paper)}>
                    {paper.title}
                  </h3>
                  <p className="text-[11px] text-stone-200 font-sans mb-3 font-black">
                    By {paper.authors.join(", ")} | {paper.schools[0]}
                  </p>
                  <p className="text-stone-100 text-xs font-bold line-clamp-2 leading-relaxed mb-4">
                    {paper.abstract}
                  </p>
                </div>

                <div className="flex items-center justify-between pt-3.5 border-t border-slate-850 mt-auto">
                  <div className="flex items-center gap-2 text-[10px] text-stone-200 font-mono font-bold">
                    <GraduationCap className="w-4 h-4 text-blue-500" />
                    <span>Published globally</span>
                  </div>
                  <div className="flex gap-2">
                    <button
                      onClick={() => startEditing(paper)}
                      className="p-2.5 bg-slate-900 hover:bg-slate-800 border border-slate-850 hover:border-blue-500 text-stone-200 rounded-xl transition-all duration-300 cursor-pointer hover:text-blue-400 transform hover:scale-[1.05] font-bold"
                      title="Edit Paper Details"
                    >
                      <Edit2 className="w-3.5 h-3.5" />
                    </button>
                    <button
                      onClick={() => {
                        if (confirm("Are you sure you want to retract and delete this uploaded manuscript from your scholar records? This action is permanent.")) {
                          onDeletePaper(paper.id);
                        }
                      }}
                      className="p-2.5 bg-slate-900 hover:bg-rose-950/40 border border-slate-850 hover:border-rose-500/50 text-stone-200 hover:text-rose-400 rounded-xl transition-all duration-300 cursor-pointer transform hover:scale-[1.05] font-bold"
                      title="Delete / Retract Paper"
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                    </button>
                    <button
                      onClick={() => onReadPaper(paper)}
                      className="px-4 py-2 animated-gradient-btn text-white rounded-full text-xs font-extrabold flex items-center gap-1 cursor-pointer"
                    >
                      Open Reader <ArrowRight className="w-3.5 h-3.5" />
                    </button>
                  </div>
                </div>
              </motion.div>
            ))
          ) : (
            <div className="col-span-2 text-center py-16 bg-white/5 border border-white/15 rounded-2xl">
              <Upload className="w-10 h-10 text-stone-300 mx-auto mb-3 animate-pulse" />
              <p className="text-stone-100 text-sm font-black">You haven't uploaded any research papers yet</p>
              <p className="text-stone-300 text-xs mt-1 font-bold">Share your scientific findings with the global community to build your bibliography.</p>
            </div>
          )
        )}

        {/* Downloads Tab */}
        {activeTab === "downloads" && (
          downloadedPapers.length > 0 ? (
            downloadedPapers.map((paper) => (
              <motion.div
                key={paper.id}
                layoutId={`library-download-${paper.id}`}
                className="vibrant-glass-bright border border-white/10 hover:border-cyan-400/50 rounded-2xl p-5 flex flex-col justify-between hover:shadow-[0_0_20px_rgba(34,211,238,0.12)] transition-all duration-300"
              >
                <div>
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-[9px] font-mono uppercase bg-cyan-400/10 text-cyan-300 border border-cyan-400/30 px-2.5 py-1 rounded font-bold">
                      {paper.category}
                    </span>
                    <span className="text-[10px] text-stone-200 font-mono flex items-center gap-1 font-black">
                      <FileText className="w-3 h-3 text-cyan-400" /> Offline Copy
                    </span>
                  </div>
                  <h3 className="font-display font-extrabold text-stone-100 text-sm md:text-base leading-snug mb-1.5 hover:text-blue-400 transition-colors cursor-pointer" onClick={() => onReadPaper(paper)}>
                    {paper.title}
                  </h3>
                  <p className="text-[11px] text-stone-200 font-sans mb-3 font-black">
                    By {paper.authors.join(", ")} | {paper.schools[0]}
                  </p>
                  <p className="text-stone-100 text-xs font-bold line-clamp-2 leading-relaxed mb-4">
                    {paper.abstract}
                  </p>
                </div>

                <div className="flex items-center justify-between pt-3.5 border-t border-slate-850 mt-auto">
                  <span className="text-[10px] text-stone-300 font-mono font-bold">
                    Downloaded {paper.publishedDate}
                  </span>
                  <button
                    onClick={() => onReadPaper(paper)}
                    className="px-4 py-2 animated-gradient-btn text-white rounded-full text-xs font-extrabold flex items-center gap-1 cursor-pointer"
                  >
                    Open Document <ArrowRight className="w-3.5 h-3.5" />
                  </button>
                </div>
              </motion.div>
            ))
          ) : (
            <div className="col-span-2 text-center py-16 bg-white/5 border border-white/15 rounded-2xl">
              <Download className="w-10 h-10 text-stone-300 mx-auto mb-3 animate-pulse" />
              <p className="text-stone-100 text-sm font-black">No downloaded papers logged</p>
              <p className="text-stone-300 text-xs mt-1 font-bold">Papers you read or download during your session will appear here for fast retrieval.</p>
            </div>
          )
        )}

        {/* Read History Tab */}
        {activeTab === "history" && (
          readHistoryPapers.length > 0 ? (
            readHistoryPapers.map((paper) => (
              <motion.div
                key={paper.id}
                layoutId={`library-history-${paper.id}`}
                className="vibrant-glass-bright border border-white/10 hover:border-cyan-400/50 rounded-2xl p-5 flex flex-col justify-between hover:shadow-[0_0_20px_rgba(34,211,238,0.12)] transition-all duration-300"
              >
                <div>
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-[9px] font-mono uppercase bg-cyan-400/10 text-cyan-300 border border-cyan-400/30 px-2.5 py-1 rounded font-bold">
                      {paper.category}
                    </span>
                    <span className="text-[10px] text-stone-200 font-mono flex items-center gap-1 font-black">
                      <BookOpen className="w-3 h-3 text-cyan-400" /> Recent Session
                    </span>
                  </div>
                  <h3 className="font-display font-extrabold text-stone-100 text-sm md:text-base leading-snug mb-1.5 hover:text-blue-400 transition-colors cursor-pointer" onClick={() => onReadPaper(paper)}>
                    {paper.title}
                  </h3>
                  <p className="text-[11px] text-stone-200 font-sans mb-3 font-black">
                    By {paper.authors.join(", ")} | {paper.schools[0]}
                  </p>
                  <p className="text-stone-100 text-xs font-bold line-clamp-2 leading-relaxed mb-4">
                    {paper.abstract}
                  </p>
                </div>

                <div className="flex items-center justify-between pt-3.5 border-t border-slate-850 mt-auto">
                  <span className="text-[10px] text-stone-300 font-mono font-bold">
                    Published {paper.publishedDate}
                  </span>
                  <button
                    onClick={() => onReadPaper(paper)}
                    className="px-4 py-2 animated-gradient-btn text-white rounded-full text-xs font-extrabold flex items-center gap-1 cursor-pointer"
                  >
                    Open Reader <ArrowRight className="w-3.5 h-3.5" />
                  </button>
                </div>
              </motion.div>
            ))
          ) : (
            <div className="col-span-2 text-center py-16 bg-white/5 border border-white/15 rounded-2xl">
              <BookOpen className="w-10 h-10 text-stone-300 mx-auto mb-3 animate-pulse" />
              <p className="text-stone-100 text-sm font-black">No reading history recorded</p>
              <p className="text-stone-300 text-xs mt-1 font-bold">Papers you open to read or analyze will be tracked in your history here.</p>
            </div>
          )
        )}

        {/* Research Notes Tab */}
        {activeTab === "notes" && (
          notes.length > 0 ? (
            notes.map((note) => {
              const paper = papers.find(p => p.id === note.paperId);
              return (
                <motion.div
                  key={note.id}
                  layoutId={`library-notes-${note.id}`}
                  className="col-span-1 md:col-span-2 bg-[#090f20]/50 backdrop-blur-xl border border-white/10 hover:border-blue-500/30 rounded-2xl p-6 flex flex-col justify-between hover:shadow-[0_0_20px_rgba(59,130,246,0.1)] transition-all duration-300"
                >
                  <div>
                    <div className="flex items-center justify-between mb-2 pb-2.5 border-b border-slate-800/60">
                      <div className="flex items-center gap-2">
                        <span className="text-[9px] font-mono uppercase bg-blue-500/10 text-blue-300 border border-blue-500/30 px-2.5 py-1 rounded font-bold">
                          {note.category}
                        </span>
                        <span className="text-[10px] text-stone-200 font-mono flex items-center gap-1 font-black">
                          Updated {note.updatedAt}
                        </span>
                      </div>
                      
                      <div className="flex items-center gap-1.5">
                        <button
                          onClick={() => {
                            const markdownText = `# Research Notebook Entry\n\n**Paper:** ${note.paperTitle}\n**Category:** ${note.category}\n**Date:** ${note.updatedAt}\n\n## Scientific Annotations & Notes\n\n${note.noteText}\n\n---\n*Compiled via APEX Global Academic Network*`;
                            const blob = new Blob([markdownText], { type: "text/markdown;charset=utf-8" });
                            const link = document.createElement("a");
                            link.href = URL.createObjectURL(blob);
                            link.download = `${note.paperTitle.replace(/[^a-zA-Z0-9]/g, "_")}_Notes.md`;
                            document.body.appendChild(link);
                            link.click();
                            document.body.removeChild(link);
                          }}
                          className="text-stone-200 hover:text-cyan-400 hover:bg-cyan-500/10 border border-slate-850 hover:border-cyan-500/30 transition-all duration-300 p-2 rounded-xl cursor-pointer font-bold"
                          title="Export Note to Markdown"
                        >
                          <Share2 className="w-3.5 h-3.5" />
                        </button>
                        
                        <button
                          onClick={() => onDeleteNote(note.id)}
                          className="text-stone-200 hover:text-rose-400 hover:bg-rose-500/10 border border-slate-850 hover:border-rose-500/30 transition-all duration-300 p-2 rounded-xl cursor-pointer font-bold"
                          title="Delete Note"
                        >
                          <Trash2 className="w-3.5 h-3.5" />
                        </button>
                      </div>
                    </div>

                    <h3 className="font-display font-extrabold text-stone-100 text-sm md:text-base leading-snug mb-3">
                      {note.paperTitle}
                    </h3>

                    {/* Rich text area for editing notes in real time */}
                    <div className="relative mt-2">
                      <textarea
                        value={note.noteText}
                        onChange={(e) => onSaveNote(note.paperId, note.paperTitle, note.category, e.target.value)}
                        placeholder="Draft your thoughts, critical analyses, or research questions about this paper..."
                        className="w-full h-32 bg-[#03060f]/60 hover:bg-[#03060f]/85 focus:bg-[#03060f] border border-slate-800 focus:border-blue-500/60 rounded-xl px-4 py-3 text-xs text-stone-100 placeholder-stone-500 focus:outline-none transition-all font-sans font-bold leading-relaxed resize-none"
                      />
                      <div className="absolute bottom-2.5 right-3 flex items-center gap-1.5 text-[9px] font-mono text-emerald-400 bg-emerald-950/40 px-2.5 py-0.5 rounded-full border border-emerald-500/20 font-bold">
                        <Check className="w-3 h-3 text-emerald-400" />
                        Auto-Saved
                      </div>
                    </div>
                  </div>

                  {paper && (
                    <div className="flex items-center justify-end pt-3 mt-4 border-t border-slate-900">
                      <button
                        onClick={() => onReadPaper(paper)}
                        className="px-4 py-2 bg-blue-500/10 hover:bg-blue-500/20 border border-blue-500/20 hover:border-blue-500/40 text-blue-300 text-xs font-bold rounded-full transition-all cursor-pointer flex items-center gap-1.5"
                      >
                        <BookOpen className="w-3.5 h-3.5" />
                        Return to Reading Room
                      </button>
                    </div>
                  )}
                </motion.div>
              );
            })
          ) : (
            <div className="col-span-2 text-center py-16 bg-white/5 border border-white/15 rounded-2xl">
              <FileText className="w-10 h-10 text-stone-300 mx-auto mb-3 animate-pulse" />
              <p className="text-stone-100 text-sm font-black">Your Research Diary is Empty</p>
              <p className="text-stone-300 text-xs mt-1 max-w-md mx-auto font-bold">
                Open any research paper inside the Reader, toggle the Astra AI Copilot, write your annotations, and they will populate your centralized portfolio here!
              </p>
            </div>
          )
        )}

      </div>

      {/* Edit Paper Modal Overlay */}
      <AnimatePresence>
        {editingPaper && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
            {/* Backdrop */}
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setEditingPaper(null)}
              className="absolute inset-0 bg-black/85 backdrop-blur-md"
            />
            
            {/* Modal Body */}
            <motion.div
              initial={{ opacity: 0, scale: 0.95, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 20 }}
              className="relative w-full max-w-2xl bg-[#090e1a]/95 border border-white/10 hover:border-cyan-400/30 rounded-3xl p-6 md:p-8 shadow-2xl overflow-y-auto max-h-[90vh] text-left z-10"
            >
              <button
                type="button"
                onClick={() => setEditingPaper(null)}
                className="absolute top-5 right-5 text-stone-400 hover:text-stone-150 p-2 rounded-full hover:bg-white/5 transition-colors cursor-pointer"
              >
                <X className="w-5 h-5" />
              </button>

              <div className="mb-6">
                <span className="text-[10px] font-mono bg-cyan-400/10 text-cyan-300 border border-cyan-400/20 px-2.5 py-1 rounded font-black tracking-wide uppercase">
                  Manuscript Editor
                </span>
                <h3 className="font-display font-extrabold text-stone-100 text-lg md:text-xl mt-3">
                  Edit Research Details
                </h3>
                <p className="text-stone-200 text-xs mt-1 font-extrabold">
                  Correct typos, update affiliations, or refine your abstract to maintain academic accuracy.
                </p>
              </div>

              <form onSubmit={handleSaveEdit} className="space-y-4">
                <div>
                  <label className="block text-[10px] font-mono text-stone-200 uppercase tracking-wide mb-1.5 font-black">
                    Research Title
                  </label>
                  <input
                    type="text"
                    required
                    value={editTitle}
                    onChange={(e) => setEditTitle(e.target.value)}
                    className="w-full bg-[#03060f]/60 border border-slate-800 rounded-xl px-4 py-3 text-xs text-stone-100 placeholder-stone-500 focus:outline-none focus:border-blue-500/80 transition-all font-sans font-bold"
                  />
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-[10px] font-mono text-stone-200 uppercase tracking-wide mb-1.5 font-black">
                      Co-Authors (comma separated)
                    </label>
                    <input
                      type="text"
                      required
                      value={editAuthors}
                      onChange={(e) => setEditAuthors(e.target.value)}
                      className="w-full bg-[#03060f]/60 border border-slate-800 rounded-xl px-4 py-3 text-xs text-stone-100 placeholder-stone-500 focus:outline-none focus:border-blue-500/80 transition-all font-sans font-bold"
                    />
                  </div>
                  <div>
                    <label className="block text-[10px] font-mono text-stone-200 uppercase tracking-wide mb-1.5 font-black">
                      School Affiliation
                    </label>
                    <input
                      type="text"
                      required
                      value={editSchool}
                      onChange={(e) => setEditSchool(e.target.value)}
                      className="w-full bg-[#03060f]/60 border border-slate-800 rounded-xl px-4 py-3 text-xs text-stone-100 placeholder-stone-500 focus:outline-none focus:border-blue-500/80 transition-all font-sans font-bold"
                    />
                  </div>
                </div>

                <div>
                  <label className="block text-[10px] font-mono text-stone-200 uppercase tracking-wide mb-1.5 font-black">
                    Research Abstract
                  </label>
                  <textarea
                    required
                    rows={5}
                    value={editAbstract}
                    onChange={(e) => setEditAbstract(e.target.value)}
                    className="w-full bg-[#03060f]/60 border border-slate-800 rounded-xl px-4 py-3 text-xs text-stone-100 placeholder-stone-500 focus:outline-none focus:border-blue-500/80 transition-all font-sans font-bold leading-relaxed resize-none"
                  />
                </div>

                <div className="flex items-center justify-between pt-4 border-t border-slate-900 mt-6">
                  <span className="text-[10px] text-stone-300 font-mono font-bold">
                    Changes sync immediately across the scholar search index.
                  </span>
                  <div className="flex gap-2.5">
                    <button
                      type="button"
                      onClick={() => setEditingPaper(null)}
                      className="px-4 py-2.5 bg-slate-950/60 hover:bg-slate-900 border border-slate-800 text-stone-200 hover:text-stone-100 rounded-xl text-xs font-black transition-all cursor-pointer"
                    >
                      Cancel
                    </button>
                    <button
                      type="submit"
                      disabled={isSaving}
                      className="px-5 py-2.5 bg-gradient-to-r from-blue-600 to-cyan-500 hover:from-blue-500 hover:to-cyan-400 text-white rounded-xl text-xs font-extrabold flex items-center gap-1.5 cursor-pointer shadow-lg disabled:opacity-55"
                    >
                      {isSaving ? (
                        <>
                          <Loader2 className="w-3.5 h-3.5 animate-spin" />
                          Saving...
                        </>
                      ) : (
                        <>
                          <Save className="w-3.5 h-3.5" />
                          Save Changes
                        </>
                      )}
                    </button>
                  </div>
                </div>
              </form>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

    </div>
  );
}
