import React, { useState, useEffect } from "react";
import { motion, AnimatePresence } from "motion/react";
import { 
  Database, ShieldCheck, CheckCircle2, AlertTriangle, X, RefreshCw, 
  Copy, Check, Trash2, HelpCircle, ExternalLink, Settings, Terminal
} from "lucide-react";
import { 
  getActiveSupabaseCredentials, 
  saveCustomSupabaseCredentials, 
  clearCustomSupabaseCredentials, 
  testSupabaseConnection 
} from "../lib/supabase-service";

interface SupabaseDashboardModalProps {
  isOpen: boolean;
  onClose: () => void;
  userId?: string;
  bookmarksCount: number;
  notesCount: number;
}

export default function SupabaseDashboardModal({
  isOpen,
  onClose,
  userId,
  bookmarksCount,
  notesCount
}: SupabaseDashboardModalProps) {
  const [url, setUrl] = useState("");
  const [anonKey, setAnonKey] = useState("");
  const [isCustom, setIsCustom] = useState(false);
  
  // Connection diagnostics
  const [isTesting, setIsTesting] = useState(false);
  const [testResult, setTestResult] = useState<{
    connected: boolean;
    message: string;
    tables: { profiles: boolean; bookmarks: boolean; notes: boolean };
  } | null>(null);

  const [copiedSql, setCopiedSql] = useState(false);
  const [copiedCreds, setCopiedCreds] = useState(false);
  const [saveSuccess, setSaveSuccess] = useState(false);
  const [showSqlHelp, setShowSqlHelp] = useState(false);

  // SQL schema DDL script for easy database initialization
  const SQL_MIGRATION_SCHEMA = `-- APEX SCHOLAR DATABASE SETUP SCRIPT
-- Execute this block in your Supabase SQL Editor to initialize all tables!

-- 1. PROFILES TABLE (User Identities)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  avatar_url TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. BOOKMARKS TABLE (Saved academic research papers)
CREATE TABLE IF NOT EXISTS public.bookmarks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  paper_id TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE (user_id, paper_id)
);

-- 3. NOTES TABLE (Active scholar annotations & notes)
CREATE TABLE IF NOT EXISTS public.notes (
  id TEXT PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  paper_id TEXT NOT NULL,
  paper_title TEXT,
  category TEXT,
  note_text TEXT,
  updated_at TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. CONFIGURE ROW LEVEL SECURITY (RLS) FOR PEER ISOLATION
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookmarks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notes ENABLE ROW LEVEL SECURITY;

-- 5. ACCESS POLICIES: Profiles
CREATE POLICY "Allow individual profile read" ON public.profiles
  FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Allow individual profile updates" ON public.profiles
  FOR ALL USING (auth.uid() = id);

-- ACCESS POLICIES: Bookmarks
CREATE POLICY "Allow individual bookmarks select" ON public.bookmarks
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Allow individual bookmarks insert" ON public.bookmarks
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow individual bookmarks delete" ON public.bookmarks
  FOR DELETE USING (auth.uid() = user_id);

-- ACCESS POLICIES: Notes
CREATE POLICY "Allow individual notes select" ON public.notes
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Allow individual notes insert" ON public.notes
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow individual notes update" ON public.notes
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Allow individual notes delete" ON public.notes
  FOR DELETE USING (auth.uid() = user_id);`;

  useEffect(() => {
    if (isOpen) {
      const creds = getActiveSupabaseCredentials();
      setUrl(creds.url);
      setAnonKey(creds.anonKey);
      setIsCustom(creds.isCustom);
      
      // Run an immediate diagnostic check to see active health!
      handleRunDiagnostic();
    }
  }, [isOpen]);

  const handleRunDiagnostic = async () => {
    setIsTesting(true);
    try {
      const res = await testSupabaseConnection();
      setTestResult(res);
    } catch (e) {
      setTestResult({
        connected: false,
        message: "An unexpected error occurred during tests.",
        tables: { profiles: false, bookmarks: false, notes: false }
      });
    } finally {
      setIsTesting(false);
    }
  };

  const handleSave = () => {
    if (!url.trim() || !anonKey.trim()) return;
    
    const success = saveCustomSupabaseCredentials(url, anonKey);
    if (success) {
      setSaveSuccess(true);
      setTimeout(() => {
        setSaveSuccess(false);
        // Force reload the window so the new client instance takes full effect
        window.location.reload();
      }, 1000);
    }
  };

  const handleResetToDefault = () => {
    clearCustomSupabaseCredentials();
    setSaveSuccess(true);
    setTimeout(() => {
      setSaveSuccess(false);
      window.location.reload();
    }, 1000);
  };

  const copySqlToClipboard = () => {
    navigator.clipboard.writeText(SQL_MIGRATION_SCHEMA);
    setCopiedSql(true);
    setTimeout(() => setCopiedSql(false), 2000);
  };

  if (!isOpen) return null;

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
        {/* Dark Backdrop */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          onClick={onClose}
          className="fixed inset-0 bg-slate-950/85 backdrop-blur-md"
        />

        {/* Modal Container */}
        <motion.div
          initial={{ opacity: 0, scale: 0.95, y: 15 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 15 }}
          className="relative bg-slate-900 border border-slate-800 rounded-3xl w-full max-w-2xl overflow-hidden shadow-2xl z-10 flex flex-col max-h-[90vh]"
        >
          {/* Accent Header Line */}
          <div className="h-1.5 w-full bg-gradient-to-r from-cyan-500 via-blue-600 to-indigo-600" />

          {/* Close Button */}
          <button
            onClick={onClose}
            className="absolute top-4 right-4 text-stone-400 hover:text-white bg-slate-950/40 hover:bg-slate-950/80 p-2 rounded-full transition-all cursor-pointer"
          >
            <X className="w-4 h-4" />
          </button>

          {/* Modal Header */}
          <div className="p-6 pb-0 flex items-center gap-3.5">
            <div className="w-11 h-11 bg-cyan-950/50 border border-cyan-800/40 rounded-xl flex items-center justify-center text-cyan-400">
              <Database className="w-6 h-6 animate-pulse" />
            </div>
            <div>
              <h2 className="font-display font-black text-lg text-white leading-none flex items-center gap-2">
                Supabase Sync Dashboard
                <span className="text-[9px] px-1.5 py-0.5 rounded font-mono font-bold tracking-wider uppercase bg-cyan-950 border border-cyan-800/40 text-cyan-300">
                  REAL-TIME DB
                </span>
              </h2>
              <p className="text-xs text-stone-400 mt-1.5">
                Manage, diagnose, and configure your persistent cloud database credentials.
              </p>
            </div>
          </div>

          {/* Scrollable Content Workspace */}
          <div className="flex-1 overflow-y-auto p-6 space-y-6">
            
            {/* Live Connection Diagnostics Summary Card */}
            <div className="bg-slate-950/50 border border-slate-800 rounded-2xl p-5 space-y-4">
              <div className="flex items-center justify-between">
                <span className="text-[10px] font-mono text-slate-500 uppercase tracking-widest flex items-center gap-1">
                  <ShieldCheck className="w-3.5 h-3.5 text-blue-400" />
                  Diagnostic Handshake Check
                </span>
                <button
                  onClick={handleRunDiagnostic}
                  disabled={isTesting}
                  className="text-xs font-bold text-cyan-400 hover:text-cyan-300 flex items-center gap-1.5 transition-colors cursor-pointer disabled:opacity-50"
                >
                  <RefreshCw className={`w-3 h-3 ${isTesting ? "animate-spin" : ""}`} />
                  <span>Run Test</span>
                </button>
              </div>

              {/* Ping Output State */}
              {isTesting ? (
                <div className="flex items-center gap-3.5 py-2">
                  <div className="w-2 h-2 bg-amber-400 rounded-full animate-ping" />
                  <span className="text-xs text-stone-300 font-mono">Pinging Supabase REST and Auth Endpoints...</span>
                </div>
              ) : testResult ? (
                <div className="space-y-4">
                  {/* Status Indicator Bar */}
                  <div className="flex items-center gap-3.5">
                    <div className={`w-3 h-3 rounded-full ${testResult.connected ? "bg-emerald-500 shadow-[0_0_10px_rgba(16,185,129,0.5)]" : "bg-red-500 shadow-[0_0_10px_rgba(239,68,68,0.5)]"}`} />
                    <span className="text-xs font-bold text-white uppercase font-mono">
                      {testResult.connected ? "CONNECTED SECURELY" : "CONNECTION OFFLINE"}
                    </span>
                  </div>
                  <p className="text-xs text-stone-300 leading-relaxed font-sans border-l-2 border-slate-800 pl-3">
                    {testResult.message}
                  </p>

                  {/* Individual Table Diagnostics */}
                  <div className="grid grid-cols-3 gap-3 pt-1">
                    <div className="bg-slate-900/60 border border-slate-800 rounded-xl p-3 flex flex-col justify-between">
                      <span className="text-[10px] font-mono text-stone-400 uppercase tracking-wider block mb-1">profiles table</span>
                      <div className="flex items-center gap-1.5 mt-2">
                        {testResult.tables.profiles ? (
                          <span className="text-xs font-bold text-emerald-400 flex items-center gap-1">
                            <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
                            Active
                          </span>
                        ) : (
                          <span className="text-xs font-bold text-red-400 flex items-center gap-1">
                            <AlertTriangle className="w-3.5 h-3.5 text-red-400" />
                            Missing
                          </span>
                        )}
                      </div>
                    </div>
                    <div className="bg-slate-900/60 border border-slate-800 rounded-xl p-3 flex flex-col justify-between">
                      <span className="text-[10px] font-mono text-stone-400 uppercase tracking-wider block mb-1">bookmarks table</span>
                      <div className="flex items-center gap-1.5 mt-2">
                        {testResult.tables.bookmarks ? (
                          <span className="text-xs font-bold text-emerald-400 flex items-center gap-1">
                            <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
                            Active
                          </span>
                        ) : (
                          <span className="text-xs font-bold text-red-400 flex items-center gap-1">
                            <AlertTriangle className="w-3.5 h-3.5 text-red-400" />
                            Missing
                          </span>
                        )}
                      </div>
                    </div>
                    <div className="bg-slate-900/60 border border-slate-800 rounded-xl p-3 flex flex-col justify-between">
                      <span className="text-[10px] font-mono text-stone-400 uppercase tracking-wider block mb-1">notes table</span>
                      <div className="flex items-center gap-1.5 mt-2">
                        {testResult.tables.notes ? (
                          <span className="text-xs font-bold text-emerald-400 flex items-center gap-1">
                            <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
                            Active
                          </span>
                        ) : (
                          <span className="text-xs font-bold text-red-400 flex items-center gap-1">
                            <AlertTriangle className="w-3.5 h-3.5 text-red-400" />
                            Missing
                          </span>
                        )}
                      </div>
                    </div>
                  </div>
                </div>
              ) : (
                <p className="text-xs text-stone-500 font-mono">No diagnostic data has been generated yet.</p>
              )}
            </div>

            {/* Sync Progress Details */}
            <div className="grid grid-cols-2 gap-4">
              <div className="bg-slate-950/30 border border-slate-800/80 rounded-2xl p-4 flex items-center gap-3">
                <div className="w-9 h-9 rounded-xl bg-blue-500/10 border border-blue-500/20 text-blue-400 flex items-center justify-center text-sm font-bold font-mono">
                  {bookmarksCount}
                </div>
                <div>
                  <h4 className="text-xs font-bold text-white">Local Saved Bookmarks</h4>
                  <p className="text-[10px] text-stone-400">Syncs to public.bookmarks</p>
                </div>
              </div>
              <div className="bg-slate-950/30 border border-slate-800/80 rounded-2xl p-4 flex items-center gap-3">
                <div className="w-9 h-9 rounded-xl bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 flex items-center justify-center text-sm font-bold font-mono">
                  {notesCount}
                </div>
                <div>
                  <h4 className="text-xs font-bold text-white">Local Research Notes</h4>
                  <p className="text-[10px] text-stone-400">Syncs to public.notes</p>
                </div>
              </div>
            </div>

            {/* Supabase API Configuration Form Fields */}
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <span className="text-xs font-bold text-white uppercase tracking-wider font-mono flex items-center gap-1">
                  <Settings className="w-3.5 h-3.5 text-cyan-400" />
                  Credentials Settings
                </span>
                {isCustom && (
                  <button
                    onClick={handleResetToDefault}
                    className="text-[10px] font-mono text-red-400 hover:text-red-300 font-extrabold flex items-center gap-1 cursor-pointer transition-colors"
                  >
                    <Trash2 className="w-3 h-3" />
                    Reset to Default Instance
                  </button>
                )}
              </div>

              {/* URL */}
              <div className="space-y-1.5">
                <label className="text-[11px] font-mono text-stone-400 uppercase tracking-wide block">Supabase Project URL</label>
                <input
                  type="text"
                  value={url}
                  onChange={(e) => setUrl(e.target.value)}
                  placeholder="https://your-project.supabase.co"
                  className="w-full bg-slate-950 border border-slate-800/80 rounded-xl px-4 py-2.5 text-xs text-stone-100 placeholder-stone-600 focus:outline-none focus:border-cyan-500/60 font-mono"
                />
              </div>

              {/* Anon Key */}
              <div className="space-y-1.5">
                <label className="text-[11px] font-mono text-stone-400 uppercase tracking-wide block">Supabase Anon Public API Key</label>
                <textarea
                  value={anonKey}
                  onChange={(e) => setAnonKey(e.target.value)}
                  placeholder="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                  rows={2}
                  className="w-full bg-slate-950 border border-slate-800/80 rounded-xl px-4 py-2.5 text-xs text-stone-100 placeholder-stone-600 focus:outline-none focus:border-cyan-500/60 font-mono resize-none leading-relaxed"
                />
              </div>

              {/* Actions Footer */}
              <div className="pt-2 flex justify-end">
                <button
                  onClick={handleSave}
                  disabled={saveSuccess}
                  className="px-5 py-3 animated-gradient-btn text-white text-xs font-black rounded-xl cursor-pointer shadow-xl flex items-center gap-2"
                >
                  {saveSuccess ? (
                    <>
                      <Check className="w-4 h-4 text-white animate-bounce" />
                      <span>Applied! Reloading...</span>
                    </>
                  ) : (
                    <>
                      <ShieldCheck className="w-4 h-4 text-white" />
                      <span>Save & Apply Configuration</span>
                    </>
                  )}
                </button>
              </div>
            </div>

            {/* PostgreSQL Setup Help Drawer (Click to Toggle) */}
            <div className="border border-slate-800/80 bg-slate-950/20 rounded-2xl overflow-hidden">
              <button
                onClick={() => setShowSqlHelp(!showSqlHelp)}
                className="w-full text-left p-4 flex items-center justify-between hover:bg-slate-950/40 transition-colors cursor-pointer"
              >
                <div className="flex items-center gap-2.5">
                  <Terminal className="w-4 h-4 text-blue-400" />
                  <span className="text-xs font-bold text-white">How do I create these missing tables?</span>
                </div>
                <span className="text-xs font-mono text-blue-400 font-extrabold">
                  {showSqlHelp ? "Hide Schema" : "Show Setup SQL"}
                </span>
              </button>

              <AnimatePresence>
                {showSqlHelp && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: "auto", opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    className="border-t border-slate-800 overflow-hidden"
                  >
                    <div className="p-4 space-y-4">
                      <p className="text-[11px] text-stone-300 leading-relaxed leading-normal">
                        To connect your custom Supabase database to APEX Research, paste the following SQL block directly into the 
                        <strong className="text-white"> SQL Editor</strong> inside your Supabase Web Console dashboard. It will build the three required schema tables and configure Row-Level Security isolation.
                      </p>

                      {/* SQL Code Block */}
                      <div className="relative">
                        <pre className="p-3 bg-slate-950 rounded-xl text-[10px] text-stone-400 font-mono overflow-x-auto border border-slate-800 max-h-52">
                          {SQL_MIGRATION_SCHEMA}
                        </pre>
                        <button
                          onClick={copySqlToClipboard}
                          className="absolute top-2.5 right-2.5 px-3 py-1.5 rounded-lg bg-slate-900 border border-slate-800 text-[10px] font-mono text-cyan-400 hover:text-white transition-all flex items-center gap-1.5 cursor-pointer"
                        >
                          {copiedSql ? (
                            <>
                              <Check className="w-3 h-3 text-emerald-400 animate-pulse" />
                              <span>Copied!</span>
                            </>
                          ) : (
                            <>
                              <Copy className="w-3 h-3" />
                              <span>Copy Code</span>
                            </>
                          )}
                        </button>
                      </div>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>

          </div>

          {/* Modal Footer */}
          <div className="p-4.5 bg-slate-950/40 border-t border-slate-800/80 flex items-center justify-between text-[11px] text-stone-400">
            <span className="flex items-center gap-1 font-mono">
              <Database className="w-3 h-3 text-cyan-400 animate-pulse" />
              Instance Status: {isCustom ? "Custom Project Cluster" : "Shared High-Performance Cluster"}
            </span>
            <span className="font-mono text-stone-500">v2.10.4-secure</span>
          </div>

        </motion.div>
      </div>
    </AnimatePresence>
  );
}
